config/routes.rb
Shidoblog::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :portfolio, :only => 'index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  attr_accessible :content, :title
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :author_email, :author_name, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create!(params[:comment])
    redirect_to articles_path
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/articles/_form.html.slim
= form_for @article, :html => { :class => 'form-horizontal' } do |f|
  div class="control-group"
    = f.label :title, :class => 'control-label'
    div class="controls"
      = f.text_field :title, :class => 'text_field'
  div class="control-group"
    = f.label :content, :class => 'control-label'
    div class="controls"
      = f.text_area :content, :class => 'text_area'

  div class="form-actions"
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn'

app/views/articles/edit.html.slim
- model_class = @article.class
div class="page-header"
  h1
    =t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}")
= render :partial => 'form'

app/views/articles/index.html.slim
- for article in @articles do
  div class="content"
    h1
      = article.title
    hr
    hr
    = article.content
    br
    span style="float:right;"
      ' Ecrit par Sidney Sissaoui le
      = article.created_at.strftime("%d-%m-%Y")
    hr
  div class="comment"
    h4
      = article.comments.count
      '  comments for this article:
    hr
    = render :partial => article.comments

  div class="accordion" id="accordion2"
    div class="accordion-group"
      div class="accordion-heading"
        a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne"
          ' React to this article
      div id="collapseOne" class="accordion-body collapse"
        div class="accordion-inner"
          = form_for [article, Comment.new] do |f|
            div class="control-group"
                = f.label :'author_email', :class => 'control-label'
                div class="controls"
                  = f.text_field :'author_email', :class => 'text_field'
            div class="control-group"
                = f.label :'author_name', :class => 'controls-label'
                div class="controls"
                  = f.text_field :'author_name', :class => 'text_field'
            div class="control-group"
              = f.label :content, :class => 'control-label'
              div class="controls"
                = f.text_area :content, :class => 'text_area'

              div class="form-actions"
                = f.submit nil, :class => 'btn btn-primary'
                = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn'

app/views/articles/new.html.slim
- model_class = @article.class
div class="page-header"
  h1
    =t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}")
= render :partial => 'form'

app/views/articles/show.html.slim
- model_class = @article.class
div class="page-header"
  h1
    =t '.title', :default => model_class.model_name.human
dl class="dl-horizontal"
  dt
    strong
      = model_class.human_attribute_name(:title)
      ' :
  dd
    = @article.title
  dt
    strong
    = model_class.human_attribute_name(:content)
    ' :
  dd
    = @article.content

div class="form-actions"
  = link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger'

app/views/comments/_comment.html.slim
- if comment
  i
    ' Posted on the
    = comment.created_at
    '  by
    strong
      a href='#{comment.author_email}'
        = comment.author_name
  br
  = h(comment.content)
  hr

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_email %><br />
    <%= f.text_field :author_email %>
  </div>
  <div class="field">
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Author email</th>
    <th>Author name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.author_email %></td>
    <td><%= comment.author_name %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author email:</b>
  <%= @comment.author_email %>
</p>

<p>
  <b>Author name:</b>
  <%= @comment.author_name %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Shid'o'Blog
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    = image_tag("logo.jpg", :border => 0, :height => "300", :width => "100%")
    div class="navbar navbar-fixed-top"
      div class="navbar-inner"
        div class="container"
          a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="brand" href="#"
            ' Shid'o'Blog
          div class="nav-collapse"
            ul class="nav"
              li
                = link_to "Articles", articles_path
              li
                = link_to "Portfolio", portfolio_index_path
    div class="container"
      div class="row"
        div class="span10"
          = yield
        div class="span2"
          h2 Lorem Ipsum
          ' Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.